version: 2
updates:
  - package-ecosystem: pip
    directory: /app
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directories:
      - /terraform/envs/local
      - /terraform/envs/aws
      - /terraform/modules/observability
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
