apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orders-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
